In [24]:
import pandas as pd
import numpy as np

In [25]:
run1_1000 = pd.read_csv("1000_run1.csv")
run2_1000 = pd.read_csv("1000_run2.csv")
run3_1000 = pd.read_csv("1000_run3.csv")

run123_1000 = (run1_1000 + run2_1000 + run3_1000)/3

In [36]:
run123_1000

,Unnamed: 0,support,abs difference test (F1 score) aggregated,f1_all_clusters,f1_individual,train_all,train_cluster_0,train_cluster_1,train_cluster_2,train_cluster_3,train_cluster_4
0,0.0,43617.0,0.013602,0.244704,0.231102,0.275185,0.288766,0.045543,0.294819,0.120365,0.221963
1,1.0,23018.0,0.153161,0.244704,0.091543,0.263928,0.249022,0.275206,0.393202,0.252553,0.134528
2,2.0,1230.0,-0.078323,0.244704,0.323027,0.316471,0.200759,0.176042,0.383802,0.245848,0.095240
3,3.0,67843.0,0.097717,0.244704,0.146987,0.116461,0.117603,0.042962,0.288652,0.126716,0.041094
4,4.0,31360.0,0.042110,0.244704,0.202595,0.372246,0.253298,0.053740,0.359002,0.106452,0.393858

In [78]:
(0.116461 - 0.042962)/0.116461

0.6311039747211513

In [64]:
run123_1000.train_all.values - run123_1000.loc[:, ["train_cluster_0", "train_cluster_1", "train_cluster_2", "train_cluster_3", "train_cluster_4"]].values[:, 0]

array([-0.01358135,  0.01490608,  0.11571193, -0.00114236,  0.11894878])

In [65]:
da_1000 = pd.DataFrame(run123_1000.train_all.values.reshape(-1, 1) - run123_1000.loc[:, ["train_cluster_0", "train_cluster_1", "train_cluster_2", "train_cluster_3", "train_cluster_4"]].values)
da_1000.columns = ["train_cluster_0", "train_cluster_1", "train_cluster_2", "train_cluster_3", "train_cluster_4"]

In [80]:
pd.DataFrame(da_1000/run123_1000.train_all.values.reshape(-1, 1)).round(3).to_csv("1000_mean_scores.csv")

In [81]:
pd.DataFrame(da_1000/run123_1000.train_all.values.reshape(-1, 1)).round(3)

,train_cluster_0,train_cluster_1,train_cluster_2,train_cluster_3,train_cluster_4
0,-0.049,0.835,-0.071,0.563,0.193
1,0.056,-0.043,-0.490,0.043,0.490
2,0.366,0.444,-0.213,0.223,0.699
3,-0.010,0.631,-1.479,-0.088,0.647
4,0.320,0.856,0.036,0.714,-0.058

In [68]:
run123_1000.train_all.values

array([0.27518501, 0.26392758, 0.31647098, 0.11646101, 0.37224629])

In [69]:
run123_1000.train_all

0    0.275185
1    0.263928
2    0.316471
3    0.116461
4    0.372246
Name: train_all, dtype: float64

In [70]:
run1_2000 = pd.read_csv("2000_run1.csv")
run2_2000 = pd.read_csv("2000_run2.csv")
run3_2000 = pd.read_csv("2000_run3.csv")

run123_2000 = (run1_2000 + run2_2000 + run3_2000)/3

In [71]:
run123_2000

,Unnamed: 0,support,abs difference test (F1 score) aggregated,f1_all_clusters,f1_individual,train_all,train_cluster_0,train_cluster_1,train_cluster_2,train_cluster_3,train_cluster_4
0,0.0,42767.333333,0.063549,0.262718,0.199169,0.283574,0.290726,0.085553,0.274189,0.106166,0.225766
1,1.0,22018.000000,0.154036,0.262718,0.108682,0.277754,0.291580,0.276718,0.257735,0.253316,0.097381
2,2.0,230.000000,-0.008988,0.262718,0.271706,0.454770,0.223481,0.181450,0.524942,0.361257,0.207066
3,3.0,66843.000000,0.116532,0.262718,0.146186,0.134995,0.037886,0.061203,0.223671,0.142254,0.041546
4,4.0,30360.000000,0.053402,0.262718,0.209316,0.399738,0.211530,0.064121,0.349442,0.078408,0.424553

In [72]:
da_2000 = pd.DataFrame(run123_2000.train_all.values.reshape(-1, 1) - run123_2000.loc[:, ["train_cluster_0", "train_cluster_1", "train_cluster_2", "train_cluster_3", "train_cluster_4"]].values)
da_2000.columns = ["train_cluster_0", "train_cluster_1", "train_cluster_2", "train_cluster_3", "train_cluster_4"]

In [79]:
pd.DataFrame(da_2000/run123_2000.train_all.values).round(3).to_csv("2000_mean_scores.csv")

In [74]:
pd.DataFrame(da_2000/run123_2000.train_all.values.reshape(-1, 1)).round(3)

,train_cluster_0,train_cluster_1,train_cluster_2,train_cluster_3,train_cluster_4
0,-0.025,0.698,0.033,0.626,0.204
1,-0.050,0.004,0.072,0.088,0.649
2,0.509,0.601,-0.154,0.206,0.545
3,0.719,0.547,-0.657,-0.054,0.692
4,0.471,0.840,0.126,0.804,-0.062

In [75]:
da_2000

,train_cluster_0,train_cluster_1,train_cluster_2,train_cluster_3,train_cluster_4
0,-0.007152,0.198021,0.009385,0.177408,0.057807
1,-0.013825,0.001036,0.020019,0.024438,0.180373
2,0.231290,0.273321,-0.070172,0.093514,0.247705
3,0.097109,0.073792,-0.088676,-0.007260,0.093449
4,0.188208,0.335617,0.050296,0.321330,-0.024815

In [76]:
run123_2000.train_all.values

array([0.28357369, 0.27775428, 0.45477044, 0.13499459, 0.39973797])

In [90]:
pd.read_csv("./ts_fresh_lvl1_full/Univariate2018_ts/Univariate_ts/EOGHorizontalSignal/EOGHorizontalSignal_TRAIN.ts")

,values__abs_energy,values__absolute_sum_of_changes,"values__agg_autocorrelation__f_agg_""mean""__maxlag_40","values__agg_autocorrelation__f_agg_""median""__maxlag_40","values__agg_autocorrelation__f_agg_""var""__maxlag_40","values__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""max""","values__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""mean""","values__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""min""","values__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""var""","values__agg_linear_trend__attr_""intercept""__chunk_len_50__f_agg_""max""",...,values__time_reversal_asymmetry_statistic__lag_1,values__time_reversal_asymmetry_statistic__lag_2,values__time_reversal_asymmetry_statistic__lag_3,values__value_count__value_-1,values__value_count__value_0,values__value_count__value_1,values__variance,values__variance_larger_than_standard_deviation,values__variation_coefficient,0
0,4.544488e+08,1645.773282,0.993157,0.994249,0.000027,-216.505468,-222.319519,-227.868591,38.677666,-170.482517,...,8.069932e+05,1.615541e+06,2.423398e+06,0.0,0.0,0.0,172039.269935,1.0,0.947779,1
1,4.530452e+06,768.866160,0.927147,0.931108,0.002356,-1.559694,-4.765186,-7.967674,15.963656,11.529108,...,5.838302e+02,1.183952e+03,1.812173e+03,0.0,0.0,0.0,1653.561776,1.0,0.915986,1
2,2.807227e+07,1075.007260,0.968885,0.971513,0.000481,-40.706931,-44.970549,-48.694616,33.390463,-21.251645,...,1.528772e+04,3.057047e+04,4.581136e+04,0.0,0.0,0.0,10934.311612,1.0,0.974100,1
3,5.006712e+08,1323.242360,0.978288,0.978620,0.000162,124.826478,119.227497,114.377988,41.128893,118.984998,...,-1.425493e+06,-2.855134e+06,-4.284840e+06,0.0,0.0,0.0,139408.231328,1.0,-0.730663,1
4,1.160591e+07,997.175600,0.953413,0.957842,0.001206,91.747861,86.579883,81.234341,56.593220,110.740045,...,-4.439539e+02,-8.007037e+02,-9.935186e+02,0.0,0.0,0.0,9237.439092,1.0,13.976176,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,7.410849e+04,883.148962,0.729263,0.689379,0.019323,-5.216252,-7.322634,-9.558658,3.025151,-1.678277,...,1.822485e+00,4.086540e+00,5.821344e+00,0.0,0.0,0.0,59.279193,1.0,-88.302785,12
720,1.785382e+06,841.747590,0.937945,0.936015,0.001221,-24.804425,-26.870924,-28.908732,3.276227,-20.489428,...,1.198882e+03,2.379501e+03,3.582358e+03,0.0,0.0,0.0,1055.619615,1.0,1.682992,12
721,1.654296e+06,969.870342,0.944994,0.938169,0.000736,-12.339951,-14.530819,-16.569577,2.863218,-7.937610,...,5.556757e+02,1.143137e+03,1.729597e+03,0.0,0.0,0.0,623.458644,1.0,0.943760,12
722,1.963084e+05,991.371992,0.917677,0.904184,0.001265,14.388201,12.571017,10.589228,3.038924,17.104222,...,-5.692132e+00,-9.825983e+00,-1.438037e+01,0.0,0.0,0.0,149.494158,1.0,-4.449023,12
723,4.981246e+05,949.672521,0.865503,0.856884,0.005510,0.869189,-2.044713,-4.651960,5.399690,5.980680,...,6.520393e+01,1.287725e+02,1.932926e+02,0.0,0.0,0.0,175.917324,1.0,0.889015,12